### ISSUE TITLE
Redis backend

### ISSUE THREAD

**Issue by farmani** [urbanindo/yii2-queue#20]
is it possible to add a redis backend for this extension I really need it to use with a local storage not aws sqs so would you please provide a redis backend for it too?

**Comment by petrabarus** [comment]
Hi, unfortunately I don't really use redis at the moment. But I'm gonna try.

**Comment by petrabarus** [comment]
@farmani Redis backend is now implemented. Sorry for taking so long.

**Comment by farmani** [comment]
@petrabarus thanks bro, its a great job

**Comment by petrabarus** [comment]
Don't forget to manually add `yii2-redis` in the component.
