### ISSUE TITLE
MySQL queue

### ISSUE THREAD

**Issue by mehrna** [urbanindo/yii2-queue#25]
TNX for your great component. 
As you told in your "Road Map", then when will you implement MySQL as a queue provider?!

**Comment by petrabarus** [comment]
Hi,

We are still not putting this under priority at the moment. But you are welcome to create a pull request.

**Comment by petrabarus** [comment]
@mehrna MySQL queue is now implemented.

**Comment by mehrna** [comment]
@petrabarus Thanks for your great job!
I'll check and use it in my recent project.
