### ISSUE TITLE
Document (the lack of) init scripts for Listener

### ISSUE THREAD

**Issue by mehrna** [urbanindo/yii2-queue#30]
The doc is nice but leaves for me the following topics open:
1. how to start the listener at boot ( if it is ok! ), is there init scripts based on some OSes?
2. how can I check whether the listener is running or not?

Here I prefer a sample systemd service for Centos 7:

`nano /lib/systemd/system/queue-listener.service`

```shell
[Unit]
Description=queue-listener
After=network.target httpd.service mysqld.service

[Service]
User=apache
Group=apache
Type=oneshot
Environment="PATH=/sbin:/usr/sbin:/usr/local/sbin:/usr/local/bin:/usr/bin:/bin"
ExecStart=/var/www/html/ProjectFolderName/yii queue/listen
RemainAfterExit=yes

[Install]
WantedBy=multi-user.target
```

Also we could write an script and create a cron job to check if the service is running or not.
Thanks for any help you can provide.

**Comment by petrabarus** [comment]
Hi @mehrna,

Thank you for the suggestion. We didn't have time to write the docs on how to deploy. You can always create something like [init script](https://www.linux.com/learn/managing-linux-daemons-init-scripts) and write the PID into a file like `/var/run/yii2-queue.pid`.

In our own deployment we use [supervisord](http://supervisord.org/). It is a very powerful process manager when you can do things like this:
1. Make sure the service stays running (supervisord will automatically restart the process if the process gets terminated).
2. Execute multiple process dynamically. You can set a configuration how many listener is running. When the queue gets long, you can increase the number of listener.
3. See how many worker are running.
4. More configuration on the process themselves.

**Comment by mehrna** [comment]
Hi Dear @petrabarus,
Thank you for your fast reply.

> In our own deployment we use supervisord.

I think it has many benefits. I'll check and use it as soon as possible, and may ask you some question during deploying process. ;)

**Comment by petrabarus** [comment]
I'm glad I could help.
I would also be so glad if you can help writing the deploying guide using supervisord. :)

**Comment by mehrna** [comment]
>I'm glad I could help.

It's very kind of you.

>I would also be so glad if you can help writing the deploying guide using supervisord.

Sure! My pleasure!
I'll do my best. :)
