### ISSUE TITLE
Migrations for queue table

### ISSUE THREAD

**Issue by dbd5** [urbanindo/yii2-queue#40]
Hello,

I can't find anywhere the migrations for the queue table for using Database queue, what am I missing?

Thanks

**Comment by mehrna** [comment]
As in [this file's](https://github.com/urbanindo/yii2-queue/blob/master/src/Queues/DbQueue.php) doc comment says:
The schema of the table should follow:

```sql

  CREATE TABLE queue (
      id BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
      status TINYINT NOT NULL DEFAULT 0,
      timestamp DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
      data BLOB
  );

```
