### ISSUE TITLE
Make PCNTL optional

### ISSUE THREAD

**Issue by sadovnik** [urbanindo/yii2-queue#51]
PCNTL is used to handle SIGTERM and SIGINT signals nicely. Seems like it is a minor feature and might become optional. Isn't it?

**Comment by petrabarus** [comment]
What really improves if we make it optional?

**Comment by petrabarus** [comment]
Ah I guess because not all people install pnctl extension in their PHP? Yes, we can make it optional then.

**Comment by mehrna** [comment]
By the way I think that the name of extension is PCNTL and not PNCTL! ;)

**Comment by petrabarus** [comment]
yes, lol!
