### ISSUE TITLE
./yii queue/listen

### ISSUE THREAD

**Issue by drawlusyk** [urbanindo/yii2-queue#60]
Hello. Having a problem starting the listener. 

Please see error below...

```
Exception 'yii\base\InvalidConfigException' with message 'Failed to instantiate component or class "queue".'

in /Users/dr/MySync/Sites/git/taxiinteractive-api/basic/vendor/yiisoft/yii2/di/Instance.php:134

Stack trace:
#0 /Users/dr/MySync/Sites/git/taxiinteractive-api/basic/vendor/urbanindo/yii2-queue/src/Console/Controller.php(80): yii\di\Instance::ensure('queue', 'UrbanIndo\\Yii2\\...')

```

I have placed controllerMap into the console.php config file
```
    'controllerMap' => [
        'queue' => 'UrbanIndo\Yii2\Queue\Console\Controller'
    ],
```
Once putting that line into the console.php no ./yii command work. All throw above error.

./yii This is Yii version 2.0.11.2.

Would be great if you could check to see if this is bug or config error.

Thanks
Regards
Dennis

**Comment by odannyc** [comment]
+1 I'm getting the same error.

`Exception 'yii\base\InvalidConfigException' with message 'Failed to instantiate component or class "queue".'`

**Comment by odannyc** [comment]
@drawlusyk 

Figured it out, check out my comment above.

**Comment by drawlusyk** [comment]
Thanks for the note. Hours spent but i am still missing something as I am getting the same error.

**Comment by petrabarus** [comment]
This is related to this PR https://github.com/urbanindo/yii2-queue/pull/46

**Comment by petrabarus** [comment]
Sorry, I think I was mistaken. Where do you put the tasks? Is the queue working before today?

**Comment by drawlusyk** [comment]
WOW this has been a real struggle. After reviewing the following page and digging through some code to understand the structure i seem to have sorted it out.
http://cholo.vn/blog/yii2-queue-with-redis
One thing that i was missing is putting all config into console.php and not web.php. 

Question: now that the queue/listen is starting, it constantly scrolls. Is this by design? Or should it just listen and process when a new job hits redis? Its using about 20% cpu on my laptop.

Regards
Dennis

**Comment by marekpetras** [comment]
@drawlusyk you want to set $waitSecondsIfNoQueue in the Queue as implented in #55

**Comment by drawlusyk** [comment]
Anyone know how to make the queue/listen start on boot and run in background? I have tried a script that had...

`nohup /usr/bin/php /api/basic/yii queue/listen &`

but didnt seem to work.

Ideas?

thx
Dennis

**Comment by marekpetras** [comment]
@drawlusyk you got the command right, however how to run a script on boot depends entirely on your OS :) not really a topic for this thread

**Comment by mehrna** [comment]
@drawlusyk however its a little late to answer to your question about running listener on boot as a service in background but here in #30 we were talked about! and @marekpetras is right, its completely depends on your OS!
