### ISSUE TITLE
How to install actual version?

### ISSUE THREAD

**Issue by Wakirin** [urbanindo/yii2-queue#63]
`php composer.phar require --prefer-dist urbanindo/yii2-queue "*"`

Install with composer,  there no property `waitSecondsIfNoQueue`.

It's downloaded
```
public function actionListen($cwd = null, $timeout = null, $env = [])
    {
        $this->stdout("Listening to queue...\n");
        $this->initSignalHandler();
        $command = PHP_BINARY . " {$this->getScriptPath()} {$this->_name}/run";
        declare(ticks = 1);
        while (true) {
            $this->stdout("Running new process...\n");
            $this->runQueueFetching($command, $cwd, $timeout, $env);
        }
        $this->stdout("Exiting...\n");
    }
```

It's now on github.
```
    public function actionListen($cwd = null, $timeout = null, array $env = null)
    {
        $this->stdout("Listening to queue...\n");
        $this->initSignalHandler();
        $command = PHP_BINARY . " {$this->getScriptPath()} {$this->_name}/run";
        declare(ticks = 1);
        $queueSize = intval($this->queue->getSize());
        while (true) {
            if($this->queue->waitSecondsIfNoQueue > 0){
                $this->stdout("Queue {$queueSize} \n");
                if($queueSize == 0){
                    $this->stdout("NO Queue, Waiting {$this->queue->waitSecondsIfNoQueue}s to save cpu... \n");
                    sleep($this->queue->waitSecondsIfNoQueue);
                    $queueSize = $this->queue->getSize();
                }else{
                    $queueSize--;
                    if($queueSize<=0){
                        $queueSize = $this->queue->getSize();
                    }
                }
            }
            $this->stdout("Running new process...\n");
            $this->runQueueFetching($command, $cwd, $timeout, $env);
            if ($this->sleepTimeout > 0) {
                sleep($this->sleepTimeout);
            }
        }
        $this->stdout("Exiting...\n");
    }
```

**Comment by TonisOrmisson** [comment]
probably due to the latest changes not being released/tagged as release. 
Latest tagged release is from Feb. 2016 1.3
https://github.com/urbanindo/yii2-queue/releases

try `"dev-master"` instead of `"*"` ?

**Comment by Wakirin** [comment]
@TonisOrmisson not released, but new feature (waitSecondsIfNoQueue) in readme, it's looks strange.
I already uploaded it manually.

**Comment by TonisOrmisson** [comment]
not strange. 
What you tell your composer is to install that
https://github.com/urbanindo/yii2-queue/tree/1.3.0
no waitSecondsIfNoQueue there :)

**Comment by Wakirin** [comment]
Usually on main page project, actual readme for latest released version.

**Comment by TonisOrmisson** [comment]
Usually - main view is for "master" branch. Master branch - very often != latest stable release. 
trying to help here :)

**Comment by Wakirin** [comment]
Ok, maybe you are right. 
Look at [https://packagist.org/packages/urbanindo/yii2-queue](https://packagist.org/packages/urbanindo/yii2-queue)
There also readme not for 1.3.0, it is correct? I don't think so.
Anyway, thanks for answer. I close issue.

**Comment by TonisOrmisson** [comment]
There is a readme for 1.3
https://github.com/urbanindo/yii2-queue/blob/1.3.0/README.md
