### ISSUE TITLE
DbQueue migration

### ISSUE THREAD

**Issue by deniskoronets** [urbanindo/yii2-queue#66]
I've spend around 0.5 hour to find this comment:
 * CREATE TABLE queue (
 *     id BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
 *     status TINYINT NOT NULL DEFAULT 0,
 *     timestamp DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
 *     data BLOB
 * );

could you please put this info into readme.md in root folder or make a migration for that?

**Comment by petrabarus** [comment]
Thanks for the suggestion. I am open for pull requests if you like to do it :)

**Comment by deniskoronets** [comment]
@petrabarus i think i will do pull requests, b/c i use this library in project.

**Comment by petrabarus** [comment]
Thanks a lot! Really appreciate that!

**Comment by zhujp** [comment]
This schema the timestamp is Mysql key ,how create?

**Comment by andrewfenn** [comment]
Thanks dude, took me way longer than I care for to figure this out.
