### ISSUE TITLE
queue/peek is dequeue-ing an item

### ISSUE THREAD

**Issue by madeadi** [urbanindo/yii2-queue#69]
I'm using DbQueue. When issuing `> ./yii queue/peek` from terminal, the command is supposed to peek the queue without changing the items in the queue. 

Expected result:
The items in the queue stays the same.

Actual result:
One item in the queue is dequeued. And the dequeued item is not processed by any task.

**Comment by petrabarus** [comment]
Hey, what driver did you use?

**Comment by madeadi** [comment]
@petrabarus I'm using DbQueue, MySQL.
