### ISSUE TITLE
Multithreading

### ISSUE THREAD

**Issue by marekpetras** [urbanindo/yii2-queue#70]
Hi,

have you thought of multi threading the queue processing by using Process::start() instead of run ?

Works beautifully for me.

I have a shit load of small jobs, a lot of them waiting for responses from external APIs so I implemented threading to get it done faster.

Or was there a specific reason why you didnt want to do this?

Cheers,
Marek

**Comment by petrabarus** [comment]
Hi, we haven't thought of using multithreading we have a very different use case. But it's really a great addition. I would love it if you created a pull request for this feature.

**Comment by marekpetras** [comment]
@petrabarus hey mate, just poking you, maybe you missed the PR

**Comment by petrabarus** [comment]
@marekpetras hey, thanks for poking. Apology for missing this, I was on leave last week. Is it possible if you write some tests for this?

**Comment by marekpetras** [comment]
@petrabarus hey there, running 2.0.0 in production now on php7.1, so far so good :) if anything pops up, just poke me, i can look after this

cheers, happy we finally got it out :)

**Comment by petrabarus** [comment]
Anytime! Thanks for the help! Really appreciate it!
