### ISSUE TITLE
Getting error when running tasks

### ISSUE THREAD

**Issue by andrewfenn** [urbanindo/yii2-queue#71]
Hi,

I'm not sure exactly how to use this. I have everything hooked up. Posting jobs works great. Listening works as expected, but running the code after picking up a message errors, and I think it's due to me not understanding how routing works...

I have a FooController.php in controllers folder same as the example..

When I run: ./yii queue/run-task foo/bar

    Running task queue...PHP Fatal error:  Call to a member function runAction() on null in /var/www/***/vendor/urbanindo/yii2-queue/src/Queue.php on line 209
    PHP Fatal Error 'yii\base\ErrorException' with message 'Call to a member function runAction() on null'

    in /var/www/***/vendor/urbanindo/yii2-queue/src/Queue.php:209

    Stack trace:
    #0 [internal function]: yii\base\ErrorHandler->handleFatalError()
    #1 {main}

Any pointers on what I am doing wrong?

**Comment by marekpetras** [comment]
hey,

did you setup your module with the tasks in the app?

https://github.com/urbanindo/yii2-queue/blob/master/src/Queue.php#L103
