### ISSUE TITLE
PHP 7.2 compatibility problem 

### ISSUE THREAD

**Issue by acim** [urbanindo/yii2-queue#75]
Please change all yii\base\Object usage to \yii\base\BaseObject to provide yii >=2.0.13 and PHP 7.2 compatibility.

**Comment by acim** [comment]
If I do PR, will someone merge that? I mean there is still no response to this issue.

**Comment by petrabarus** [comment]
@acim 
I apologize for the very late response. Yes, please do PR. And upgrade the min requirement on composer for PHP and Yii2. I will tag it as major version.

**Comment by acim** [comment]
After several tries I got all green and kept compatibility from 5.5-7.2.

**Comment by niektenhoopen** [comment]
@petrabarus Do you have a time schedule for processing the PR and creating a new version?

**Comment by petrabarus** [comment]
@niektenhoopen sorry, this fell from my calendar. the update looks okay, already reviewed it. will tag the new version.

**Comment by petrabarus** [comment]
There you go it's now tagged as  2.0.0-php7

**Comment by acim** [comment]
Why am I not visible in the list of contributors?

**Comment by niektenhoopen** [comment]
@acim Probably because @petrabarus merged to the php7-compatible branch instead of the master branch

**Comment by niektenhoopen** [comment]
@petrabarus FYI: I get the following error in composer:

```
Reading composer.json of urbanindo/yii2-queue (2.0.0-php7)
Skipped tag 2.0.0-php7, invalid tag name
```

**Comment by TonisOrmisson** [comment]
@niektenhoopen 
`"urbanindo/yii2-queue": "dev-php7-compatible",`
